import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ChevronLeft, Minus, Plus, ShoppingBag, X } from 'lucide-react';
import './styles.css';

const products = [
  { id: 'runner-tee', name: 'PEAK RUNNER TEE', price: 4200, label: 'ESSENTIAL', stock: 18, image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=1000&q=85', tone: 'tee' },
  { id: 'training-hoodie', name: 'PEAK TRAINING HOODIE', price: 8600, sale: 6880, label: 'LIMITED', stock: 4, image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=1000&q=85', tone: 'hoodie' },
  { id: 'system-pants', name: 'PEAK SYSTEM PANTS', price: 7600, label: 'FIELD ISSUE', stock: 11, image: 'https://images.unsplash.com/photo-1517438476312-10d79c006eb8?auto=format&fit=crop&w=1000&q=85', tone: 'pants' },
  { id: 'performance-cap', name: 'PEAK PERFORMANCE CAP', price: 3200, label: 'LIMITED', stock: 2, image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=1000&q=85', tone: 'cap' },
  { id: 'ridge-shell', name: 'PEAK RIDGE SHELL', price: 12400, label: 'TECHNICAL', stock: 7, image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=1000&q=85', tone: 'shell' },
  { id: 'glacier-sock', name: 'GLACIER CREW SOCK', price: 1600, label: 'CORE', stock: 23, image: 'https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&w=1000&q=85', tone: 'sock' },
];
const athletes = [
  { name: 'AMANI K.', sport: 'DISTANCE RUNNING', age: '22', number: '01', image: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=900&q=85' },
  { name: 'MUSA O.', sport: 'RUGBY', age: '25', number: '02', image: 'https://images.unsplash.com/photo-1546483875-ad9014c88eba?auto=format&fit=crop&w=900&q=85' },
  { name: 'NIA W.', sport: 'FOOTBALL', age: '20', number: '03', image: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=900&q=85' },
  { name: 'KAI M.', sport: 'SKATE', age: '23', number: '04', image: 'https://images.unsplash.com/photo-1520045892732-304bc3ac5d8e?auto=format&fit=crop&w=900&q=85' },
];
const media = [
  { title: 'THE LONG WAY DOWN', athlete: 'AMANI K.', category: 'RUNNING / 2025', image: athletes[0].image },
  { title: 'NO CLEAN LINES', athlete: 'MUSA O.', category: 'RUGBY / 2025', image: athletes[1].image },
  { title: 'NINETY MINUTES', athlete: 'NIA W.', category: 'FOOTBALL / 2024', image: athletes[2].image },
];
const fmt = n => `KES ${n.toLocaleString()}`;

function App(){
 const [entered,setEntered]=useState(false); const [page,setPage]=useState('home'); const [cart,setCart]=useState([]); const [cartOpen,setCartOpen]=useState(false); const [activeProduct,setActiveProduct]=useState(null); const [notice,setNotice]=useState(''); const [menu,setMenu]=useState(false);
 useEffect(()=>{const t=setTimeout(()=>setEntered(true),1900); return()=>clearTimeout(t)},[]);
 useEffect(()=>{ if(!notice) return; const t=setTimeout(()=>setNotice(''),2400); return()=>clearTimeout(t)},[notice]);
 const count=cart.reduce((s,x)=>s+x.qty,0); const subtotal=cart.reduce((s,x)=>s+(x.sale||x.price)*x.qty,0); const delivery=subtotal?450:0;
 const go=(p)=>{setPage(p);setActiveProduct(null);setMenu(false);window.scrollTo({top:0,behavior:'smooth'})};
 const add=(p,qty=1)=>{ const existing=cart.find(x=>x.id===p.id); const have=existing?.qty||0; if(have+qty>p.stock){setNotice(`Only ${p.stock} available.`);return} setCart(existing?cart.map(x=>x.id===p.id?{...x,qty:x.qty+qty}:x):[...cart,{...p,qty}]);setNotice(`${p.name} added to bag`); };
 const change=(id, delta)=>setCart(c=>c.flatMap(x=>x.id===id?(x.qty+delta<=0?[]:[{...x,qty:Math.min(x.stock,x.qty+delta)}]):[x]));
 if(!entered) return <Loader/>;
 return <div className="app"><Atmosphere/><Header page={page} go={go} count={count} openCart={()=>setCartOpen(true)} menu={menu} setMenu={setMenu}/>{page==='home'&&<Home go={go}/>} {page==='shop'&&<Shop products={products} open={setActiveProduct}/>} {page==='media'&&<Media/>} {page==='about'&&<About/>} {['policy','terms'].includes(page)&&<Legal type={page}/>} {activeProduct&&<Product product={activeProduct} add={add} close={()=>setActiveProduct(null)}/>}<Cart open={cartOpen} close={()=>setCartOpen(false)} cart={cart} subtotal={subtotal} delivery={delivery} change={change}/>{notice&&<div className="toast">{notice}</div>}</div>
}
const peakLogo = 'https://cdn.builder.io/api/v1/image/assets%2F29d28ec06a564e72b8f38bb46f9efa52%2Ffce8ea4291fa47c188451d81c00f5db8?format=webp&width=800&height=1200';
function Loader(){return <div className="loader"><Atmosphere/><img className="loader-logo" src={peakLogo} alt="PEAK"/><div className="loader-ring"/><p>ASCENT / 01</p></div>}
function Atmosphere(){return <><div className="grain"/><div className="snow">{Array.from({length:48},(_,i)=><i key={i} style={{'--x':`${(i*37)%100}%`,'--s':`${2+i%4}px`,'--d':`${7+i%9}s`,'--delay':`${-i%8}s`}}/>)}</div></>}
function Header({go,count,openCart,menu,setMenu}){return <header><button className="wordmark" onClick={()=>go('home')} aria-label="PEAK home"><img src={peakLogo} alt="PEAK"/></button><nav className={menu?'mobile-open':''}>{['SHOP','MEDIA','ABOUT'].map(n=><button key={n} onClick={()=>go(n.toLowerCase())}>{n}</button>)}</nav><div className="header-tools"><button className="bag" onClick={openCart} aria-label="Open shopping bag"><ShoppingBag size={16}/><b>{count}</b></button><button className="menu-trigger" onClick={()=>setMenu(!menu)}>{menu?'CLOSE':'MENU'}</button></div></header>}
function Home({go}){const nav=['SHOP','MEDIA','ABOUT','POLICY','TERMS OF SERVICE'];return <main className="home"><div className="terrain"/><div className="home-copy"><p className="eyebrow">PEAK / THE COLLECTIVE</p><h1>MOVE<br/>DIFFERENT.</h1><p className="intro">An athletes and fashion collective<br/>for the ones who make their own terrain.</p></div><div className="peak-directory">{nav.map((n,i)=><button key={n} style={{'--i':i}} onClick={()=>go(n==='TERMS OF SERVICE'?'terms':n.toLowerCase())}><span>0{i+1}</span>{n}<ArrowUpRight size={17}/></button>)}</div><div className="scroll-hint">SCROLL TO DESCEND <span/></div><AthleteArchive/></main>}
function AthleteArchive(){return <section className="athlete-archive"><div className="section-head"><p className="eyebrow">THE COLLECTIVE / 002</p><h2>PEAK<br/><em>ATHLETES</em></h2><p>THE PEOPLE WHO CARRY<br/>THE WEATHER WITH THEM.</p></div><div className="athlete-grid">{athletes.map(a=><article className="athlete-card" key={a.name}><img src={a.image} alt={a.name}/><div className="athlete-shade"/><div className="athlete-index">{a.number}</div><div className="athlete-details"><h3>{a.name}</h3><p>{a.sport}</p><span>AGE {a.age}</span></div></article>)}</div></section>}
function Shop({products,open}){return <main className="page shop"><div className="page-intro"><p className="eyebrow">ISSUE 001 / AVAILABLE NOW</p><h1>THE<br/><em>STORE</em></h1><p>UTILITY FOR THE UPWARD.</p></div><div className="product-grid">{products.map(p=><button className="product" onClick={()=>open(p)} key={p.id}><div className="product-img"><img src={p.image} alt={p.name}/><span>VIEW</span></div><div className="product-meta"><p>{p.name}</p><small>{p.label} {p.stock<5&&`/ ${p.stock} LEFT`}</small><strong>{p.sale&&<del>{fmt(p.price)}</del>}{fmt(p.sale||p.price)}</strong></div></button>)}</div></main>}
function Product({product,add,close}){const [qty,setQty]=useState(1);return <main className="product-detail"><button className="back" onClick={close}><ChevronLeft size={18}/> BACK TO STORE</button><div className="detail-image"><img src={product.image} alt={product.name}/></div><div className="detail-info"><p className="eyebrow">{product.label} / {product.stock>0?`${product.stock} AVAILABLE`:'SOLD OUT'}</p><h1>{product.name}</h1><p className="detail-price">{product.sale&&<del>{fmt(product.price)}</del>}{fmt(product.sale||product.price)}</p><p className="description">Built for the hours outside the lines. A precise everyday layer with a quiet PEAK signature.</p><div className="sizes"><span>SELECT SIZE</span>{['S','M','L','XL'].map(x=><button key={x}>{x}</button>)}</div><div className="buy-row"><div className="quantity"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus size={14}/></button><span>{qty}</span><button onClick={()=>setQty(Math.min(product.stock,qty+1))}><Plus size={14}/></button></div><button className="add" onClick={()=>add(product,qty)} disabled={!product.stock}> {product.stock?'ADD TO BAG':'SOLD OUT'} <ArrowUpRight size={17}/></button></div></div></main>}
function Cart({open,close,cart,subtotal,delivery,change}){return <aside className={`cart ${open?'open':''}`} aria-hidden={!open}><div className="cart-head"><p className="eyebrow">YOUR EQUIPMENT</p><button onClick={close}><X/></button></div>{!cart.length?<div className="empty">YOUR BAG IS QUIET.<br/><button onClick={close}>RETURN TO THE WORLD</button></div>:<><div className="cart-items">{cart.map(x=><div className="cart-item" key={x.id}><img src={x.image} alt=""/><div><p>{x.name}</p><small>{fmt(x.sale||x.price)}</small><div className="cart-qty"><button onClick={()=>change(x.id,-1)}><Minus size={12}/></button>{x.qty}<button onClick={()=>change(x.id,1)}><Plus size={12}/></button></div></div><button className="remove" onClick={()=>change(x.id,-x.qty)}>REMOVE</button></div>)}</div><div className="cart-total"><p><span>SUBTOTAL</span><b>{fmt(subtotal)}</b></p><p><span>DELIVERY / NAIROBI</span><b>{fmt(delivery)}</b></p><p className="grand"><span>TOTAL</span><b>{fmt(subtotal+delivery)}</b></p><button className="checkout">CONTINUE TO CHECKOUT <ArrowUpRight size={16}/></button></div></>}</aside>}
function Media(){return <main className="page media"><div className="page-intro"><p className="eyebrow">ATHLETE ARCHIVE / 003</p><h1>THE<br/><em>ARCHIVE</em></h1><p>UNFILTERED MOVEMENT, RECORDED.</p></div><div className="media-list">{media.map((m,i)=><article className="media-item" key={m.title}><span className="media-number">0{i+1}</span><img src={m.image} alt=""/><div><p className="eyebrow">{m.athlete}</p><h2>{m.title}</h2><p>{m.category}</p></div><button className="play">VIEW FILM <ArrowUpRight size={16}/></button></article>)}</div></main>}
function About(){return <main className="about"><div className="terrain terrain-about"/><p className="eyebrow">PEAK / EST. 2024</p><h1>ATHLETES.<br/><em>FASHION.</em><br/>CULTURE.</h1><div className="about-copy"><p>PEAK is the space between the body in motion and the world it changes.</p><p>We make uniform for people who see sport as a language: raw, social, restless and shared.</p></div><div className="marquee">MOVE / MAKE / MEET / MOVE / MAKE / MEET /</div></main>}
function Legal({type}){const terms=type==='terms';return <main className="legal"><p className="eyebrow">PEAK / LEGAL</p><h1>{terms?'TERMS OF SERVICE':'POLICY'}</h1><p className="legal-note">This template content is provided for structure only and should be reviewed and replaced by PEAK’s legal team.</p>{(terms?['Introduction','Website usage','Purchases & availability','Pricing & payments','Delivery & returns','Intellectual property','Limitation of liability','Changes & contact']:['Privacy policy','Shipping policy','Returns','Refunds','Order information','Data handling']).map((x,i)=><section key={x}><span>0{i+1}</span><div><h2>{x}</h2><p>PEAK will publish the full policy for this section before opening commerce. Please contact the collective with any questions relating to orders, personal information or use of this site.</p></div></section>)}</main>}
createRoot(document.getElementById('root')).render(<App/>);
